# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('author', models.CharField(default='blank', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('pic', models.ImageField(default='img/blog/no_img.jpg', upload_to='img/blog/')),
                ('content', models.TextField()),
                ('kind', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50)),
                ('clickTimes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=50)),
                ('power', models.IntegerField(default=0)),
                ('pic', models.ImageField(default='img/user/no_img.jpg', upload_to='img/user/')),
                ('thumb', models.ImageField(blank=True, upload_to='img/user/thumb')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='blog.Comment'),
        ),
    ]
