# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_ispass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='img/blog/no_img.jpg', upload_to='img/blog/')),
                ('kind', models.CharField(default='cover', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='pic',
        ),
        migrations.AddField(
            model_name='pic',
            name='belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
    ]
