# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170918_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.CharField(choices=[('python', 'python'), ('机器学习', '机器学习'), ('阅历', '阅历')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pic',
            name='img',
            field=models.ImageField(upload_to='blog/%Y_%m'),
        ),
    ]
