# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-19 09:26
from __future__ import unicode_literals

import blog.system.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170918_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='tic',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pic',
            name='img',
            field=models.ImageField(storage=blog.system.storage.ImageStorage(), upload_to='blog/%Y_%m'),
        ),
    ]
