# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-19 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170919_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='isReprint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='reprintSource',
            field=models.CharField(default='', max_length=100),
        ),
    ]
