# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170920_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='thumb',
        ),
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(blank=True, upload_to='user/'),
        ),
    ]
