# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170922_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='avatarSrc',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
